---

- name: Update Packages
  apt:
    update_cache: yes

- name: Install the xrdp
  apt:
    name: xrdp
    state: present

- name: Install the xfce4
  apt:
    name: xfce4
    state: present

- name: Create new xsession
  sudo: yes
  command: echo xfce4-session >/root/.xsession
  command: sed -i '/\/etc\/X11\/Xsession/i xfce4-session' /etc/xrdp/startwm.sh
  notify:
    - restart xrdp
